import 'package:flutter/material.dart';

final List<Map<String, dynamic>> hostels = [
  // New York Hostels
  {
    'id': '1',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.5,
    'title': 'Cozy Hostel',
    'price': '\$50',
    'location': 'New York',
    'landmark': 'Near Central Park',
    'originalPrice': '\$60',
    'offerPercentage': '20% OFF',
    'userCount': 120,
    'taxes': 20,
    'description':
        'A cozy and comfortable hostel located near the iconic Central Park, offering a friendly atmosphere and great amenities.',
  },
  {
    'id': '2',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.3,
    'title': 'Downtown  Hostel',
    'price': '\$55',
    'location': 'New York',
    'landmark': 'Times Square',
    'originalPrice': '\$65',
    'offerPercentage': '15% OFF',
    'userCount': 140,
    'taxes': 22,
    'description':
        'Located in the heart of Times Square, this hostel is perfect for travelers looking to explore New York\'s vibrant downtown.',
  },
  {
    'id': '3',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.7,
    'title': 'Brooklyn Hostel',
    'price': '\$60',
    'location': 'New York',
    'landmark': 'Brooklyn Bridge',
    'originalPrice': '\$70',
    'offerPercentage': '14% OFF',
    'userCount': 160,
    'taxes': 25,
    'description':
        'Enjoy stunning views of the Brooklyn Bridge from this modern hostel, offering easy access to local attractions.',
  },
  {
    'id': '4',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.6,
    'title': 'Greenwich Hostel',
    'price': '\$58',
    'location': 'New York',
    'landmark': 'Greenwich Village',
    'originalPrice': '\$68',
    'offerPercentage': '15% OFF',
    'userCount': 130,
    'taxes': 21,
    'description':
        'Nestled in the charming Greenwich Village, this hostel provides a peaceful retreat with easy access to local cafes and shops.',
  },
  {
    'id': '5',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.4,
    'title': 'Harlem Hostel',
    'price': '\$52',
    'location': 'New York',
    'landmark': 'Harlem',
    'originalPrice': '\$62',
    'offerPercentage': '16% OFF',
    'userCount': 110,
    'taxes': 19,
    'description':
        'Experience the rich culture of Harlem at this heritage hostel, offering comfortable accommodations and cultural tours.',
  },

  // Los Angeles Hostels
  {
    'id': '6',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.2,
    'title': 'Modern Hostel',
    'price': '\$60',
    'location': 'Los Angeles',
    'landmark': 'Close to Hollywood Blvd',
    'originalPrice': '\$75',
    'offerPercentage': '15% OFF',
    'userCount': 95,
    'taxes': 20,
    'description':
        'A modern and stylish hostel just a short walk from Hollywood Blvd, perfect for those looking to explore LA in style.',
  },
  {
    'id': '7',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.5,
    'title': 'Sunset Hostel',
    'price': '\$65',
    'location': 'Los Angeles',
    'landmark': 'Sunset Boulevard',
    'originalPrice': '\$80',
    'offerPercentage': '18% OFF',
    'userCount': 100,
    'taxes': 23,
    'description':
        'Located on the famous Sunset Boulevard, this hostel offers vibrant nightlife and easy access to LA attractions.',
  },
  {
    'id': '8',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.1,
    'title': 'Venice Hostel',
    'price': '\$55',
    'location': 'Los Angeles',
    'landmark': 'Venice Beach',
    'originalPrice': '\$65',
    'offerPercentage': '16% OFF',
    'userCount': 85,
    'taxes': 19,
    'description':
        'Enjoy the beach vibes at this hostel located near Venice Beach, offering a relaxed atmosphere and beach activities.',
  },
  {
    'id': '9',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.3,
    'title': 'SantaMonica Hostel',
    'price': '\$62',
    'location': 'Los Angeles',
    'landmark': 'Santa Monica Pier',
    'originalPrice': '\$72',
    'offerPercentage': '14% OFF',
    'userCount': 105,
    'taxes': 20,
    'description':
        'Situated near Santa Monica Pier, this hostel provides stunning ocean views and easy access to local shops and restaurants.',
  },
  {
    'id': '10',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.4,
    'title': 'Hills Hostel',
    'price': '\$70',
    'location': 'Los Angeles',
    'landmark': 'Hollywood Hills',
    'originalPrice': '\$85',
    'offerPercentage': '18% OFF',
    'userCount': 120,
    'taxes': 25,
    'description':
        'Experience the glamour of Hollywood Hills at this upscale hostel, offering luxurious amenities and panoramic city views.',
  },

  // Chicago Hostels
  {
    'id': '11',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.8,
    'title': 'Luxury Hostel',
    'price': '\$80',
    'location': 'Chicago',
    'landmark': 'Near Millennium Park',
    'originalPrice': '\$100',
    'offerPercentage': '20% OFF',
    'userCount': 200,
    'taxes': 20,
    'description':
        'Experience luxury at an affordable price in this hostel near Millennium Park, offering top-notch facilities and services.',
  },
  {
    'id': '12',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.6,
    'title': 'Lakefront Hostel',
    'price': '\$75',
    'location': 'Chicago',
    'landmark': 'Lake Michigan',
    'originalPrice': '\$90',
    'offerPercentage': '17% OFF',
    'userCount': 180,
    'taxes': 22,
    'description':
        'Located on the shores of Lake Michigan, this hostel offers beautiful lake views and easy access to waterfront activities.',
  },
  {
    'id': '13',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.5,
    'title': 'Chicago Hostel',
    'price': '\$68',
    'location': 'Chicago',
    'landmark': 'Downtown',
    'originalPrice': '\$80',
    'offerPercentage': '15% OFF',
    'userCount': 160,
    'taxes': 20,
    'description':
        'Stay in the heart of downtown Chicago with this centrally located hostel, perfect for exploring the city\'s attractions.',
  },
  {
    'id': '14',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.7,
    'title': 'Magnificent Hostel',
    'price': '\$78',
    'location': 'Chicago',
    'landmark': 'Magnificent Mile',
    'originalPrice': '\$95',
    'offerPercentage': '18% OFF',
    'userCount': 190,
    'taxes': 24,
    'description':
        'Located along the famous Magnificent Mile, this hostel offers easy access to shopping, dining, and entertainment options.',
  },
  {
    'id': '15',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.2,
    'title': 'Wrigley Hostel',
    'price': '\$65',
    'location': 'Chicago',
    'landmark': 'Wrigley Field',
    'originalPrice': '\$75',
    'offerPercentage': '13% OFF',
    'userCount': 150,
    'taxes': 19,
    'description':
        'A perfect spot for sports enthusiasts, this hostel is located near Wrigley Field, home of the Chicago Cubs.',
  },

  // Houston Hostels
  {
    'id': '16',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.0,
    'title': 'Budget Hostel',
    'price': '\$30',
    'location': 'Houston',
    'landmark': 'Near Downtown',
    'originalPrice': '\$40',
    'offerPercentage': '25% OFF',
    'userCount': 80,
    'taxes': 20,
    'description':
        'A budget-friendly hostel located near Downtown Houston, ideal for travelers looking to save without compromising on comfort.',
  },
  {
    'id': '17',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.3,
    'title': 'SpaceCity Hostel',
    'price': '\$45',
    'location': 'Houston',
    'landmark': 'NASA Johnson Space Center',
    'originalPrice': '\$55',
    'offerPercentage': '18% OFF',
    'userCount': 110,
    'taxes': 21,
    'description':
        'Located near NASA Johnson Space Center, this hostel is perfect for space enthusiasts and offers modern amenities.',
  },
  {
    'id': '18',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.1,
    'title': 'District Hostel',
    'price': '\$50',
    'location': 'Houston',
    'landmark': 'Museum District',
    'originalPrice': '\$60',
    'offerPercentage': '17% OFF',
    'userCount': 90,
    'taxes': 20,
    'description':
        'Stay close to Houston\'s Museum District with this comfortable hostel, offering easy access to cultural attractions.',
  },
  {
    'id': '19',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.4,
    'title': 'Galleria Hostel',
    'price': '\$55',
    'location': 'Houston',
    'landmark': 'Galleria Shopping Center',
    'originalPrice': '\$65',
    'offerPercentage': '15% OFF',
    'userCount': 100,
    'taxes': 22,
    'description':
        'Located near the Galleria Shopping Center, this hostel provides convenient access to shopping, dining, and entertainment.',
  },
  {
    'id': '20',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.2,
    'title': 'Medival Hostel',
    'price': '\$48',
    'location': 'Houston',
    'landmark': 'Texas Medical Center',
    'originalPrice': '\$58',
    'offerPercentage': '17% OFF',
    'userCount': 95,
    'taxes': 20,
    'description':
        'Perfect for medical professionals and students, this hostel is located near the Texas Medical Center with all necessary amenities.',
  },

  // Miami Hostels
  {
    'id': '21',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.6,
    'title': 'Seaside Hostel',
    'price': '\$55',
    'location': 'Miami',
    'landmark': 'Beachfront',
    'originalPrice': '\$65',
    'offerPercentage': '15% OFF',
    'userCount': 150,
    'taxes': 20,
    'description':
        'A beautiful seaside hostel offering stunning views and easy beach access, perfect for a relaxing vacation.',
  },
  {
    'id': '22',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.4,
    'title': 'Deco Hostel',
    'price': '\$60',
    'location': 'Miami',
    'landmark': 'Art Deco District',
    'originalPrice': '\$70',
    'offerPercentage': '14% OFF',
    'userCount': 140,
    'taxes': 21,
    'description':
        'Experience the vibrant Art Deco culture at this hostel located in Miami\'s famous Art Deco District.',
  },
  {
    'id': '23',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.5,
    'title': 'Havana Hostel',
    'price': '\$58',
    'location': 'Miami',
    'landmark': 'Little Havana',
    'originalPrice': '\$68',
    'offerPercentage': '15% OFF',
    'userCount': 130,
    'taxes': 20,
    'description':
        'Immerse yourself in Cuban culture at this hostel located in the heart of Little Havana, offering authentic experiences.',
  },
  {
    'id': '24',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.3,
    'title': 'Wynwood Hostel',
    'price': '\$62',
    'location': 'Miami',
    'landmark': 'Wynwood Walls',
    'originalPrice': '\$72',
    'offerPercentage': '14% OFF',
    'userCount': 120,
    'taxes': 22,
    'description':
        'Stay near the famous Wynwood Walls with this artistic hostel, perfect for art lovers and creative souls.',
  },
  {
    'id': '25',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.2,
    'title': 'Miami Hostel',
    'price': '\$50',
    'location': 'Miami',
    'landmark': 'Downtown Miami',
    'originalPrice': '\$60',
    'offerPercentage': '17% OFF',
    'userCount': 110,
    'taxes': 20,
    'description':
        'Located in downtown Miami, this hostel offers easy access to business districts, nightlife, and local attractions.',
  },

  // Denver Hostels
  {
    'id': '26',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.3,
    'title': 'MountainView Hostel',
    'price': '\$45',
    'location': 'Denver',
    'landmark': 'Near Rocky Mountain Park',
    'originalPrice': '\$55',
    'offerPercentage': '18% OFF',
    'userCount': 110,
    'taxes': 20,
    'description':
        'A hostel with breathtaking mountain views, offering a tranquil escape for nature lovers.',
  },
  {
    'id': '27',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.5,
    'title': 'Denver Hostel',
    'price': '\$50',
    'location': 'Denver',
    'landmark': '16th Street Mall',
    'originalPrice': '\$60',
    'offerPercentage': '17% OFF',
    'userCount': 120,
    'taxes': 21,
    'description':
        'Stay in the heart of Denver at this hostel located on the bustling 16th Street Mall, perfect for shopping and dining.',
  },
  {
    'id': '28',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.4,
    'title': 'RiNo Hostel',
    'price': '\$52',
    'location': 'Denver',
    'landmark': 'RiNo District',
    'originalPrice': '\$62',
    'offerPercentage': '16% OFF',
    'userCount': 130,
    'taxes': 20,
    'description':
        'Experience Denver\'s vibrant arts scene at this hostel located in the RiNo (River North) Arts District.',
  },
  {
    'id': '29',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.6,
    'title': 'Cherry Hostel',
    'price': '\$55',
    'location': 'Denver',
    'landmark': 'Creek Shopping Center',
    'originalPrice': '\$65',
    'offerPercentage': '15% OFF',
    'userCount': 140,
    'taxes': 22,
    'description':
        'Located near Cherry Creek Shopping Center, this hostel offers easy access to upscale shopping and dining options.',
  },
  {
    'id': '30',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.1,
    'title': 'University Hostel',
    'price': '\$48',
    'location': 'Denver',
    'landmark': 'University of Denver',
    'originalPrice': '\$58',
    'offerPercentage': '17% OFF',
    'userCount': 100,
    'taxes': 20,
    'description':
        'Ideal for students and academics, this hostel is located near the University of Denver with all necessary amenities.',
  },

  // Boston Hostels
  {
    'id': '31',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.7,
    'title': 'Historic Hostel',
    'price': '\$70',
    'location': 'Boston',
    'landmark': 'Near Freedom Trail',
    'originalPrice': '\$85',
    'offerPercentage': '17% OFF',
    'userCount': 180,
    'taxes': 20,
    'description':
        'A hostel with a rich history, located near Boston\'s Freedom Trail, offering a unique cultural experience.',
  },
  {
    'id': '32',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.5,
    'title': 'BeaconHill Hostel',
    'price': '\$65',
    'location': 'Boston',
    'landmark': 'Beacon Hill',
    'originalPrice': '\$75',
    'offerPercentage': '15% OFF',
    'userCount': 160,
    'taxes': 21,
    'description':
        'Stay in the picturesque Beacon Hill neighborhood with this charming hostel, offering easy access to historic sites.',
  },
  {
    'id': '33',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.6,
    'title': 'Back-Bay Hostel',
    'price': '\$68',
    'location': 'Boston',
    'landmark': 'Back Bay',
    'originalPrice': '\$78',
    'offerPercentage': '16% OFF',
    'userCount': 170,
    'taxes': 22,
    'description':
        'Located in Boston\'s vibrant Back Bay area, this hostel provides easy access to shopping, dining, and entertainment.',
  },
  {
    'id': '34',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.4,
    'title': 'Seaport Hostel',
    'price': '\$72',
    'location': 'Boston',
    'landmark': 'Seaport District',
    'originalPrice': '\$85',
    'offerPercentage': '15% OFF',
    'userCount': 190,
    'taxes': 24,
    'description':
        'Enjoy waterfront views and modern amenities at this hostel located in Boston\'s trendy Seaport District.',
  },
  {
    'id': '35',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.2,
    'title': 'Fenway Hostel',
    'price': '\$60',
    'location': 'Boston',
    'landmark': 'Fenway Park',
    'originalPrice': '\$70',
    'offerPercentage': '14% OFF',
    'userCount': 150,
    'taxes': 20,
    'description':
        'Perfect for sports fans, this hostel is located near Fenway Park, home of the Boston Red Sox, offering a lively atmosphere.',
  },

  // San Francisco Hostels
  {
    'id': '36',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.1,
    'title': 'Artistic Hostel',
    'price': '\$40',
    'location': 'San Francisco',
    'landmark': 'Near Golden Gate Bridge',
    'originalPrice': '\$50',
    'offerPercentage': '20% OFF',
    'userCount': 90,
    'taxes': 20,
    'description':
        'An artistic hostel in the heart of San Francisco, close to the Golden Gate Bridge, perfect for creative minds.',
  },
  {
    'id': '37',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.3,
    'title': 'Wharf Hostel',
    'price': '\$55',
    'location': 'San Francisco',
    'landmark': 'Fisherman\'s Wharf',
    'originalPrice': '\$65',
    'offerPercentage': '16% OFF',
    'userCount': 120,
    'taxes': 21,
    'description':
        'Stay near the bustling Fisherman\'s Wharf with this hostel, offering easy access to seafood restaurants and boat tours.',
  },
  {
    'id': '38',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.5,
    'title': 'Mission Hostel',
    'price': '\$50',
    'location': 'San Francisco',
    'landmark': 'Mission District',
    'originalPrice': '\$60',
    'offerPercentage': '17% OFF',
    'userCount': 130,
    'taxes': 22,
    'description':
        'Experience the vibrant culture of the Mission District at this hostel, offering colorful murals and diverse dining options.',
  },
  {
    'id': '39',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.4,
    'title': 'Union Hostel',
    'price': '\$58',
    'location': 'San Francisco',
    'landmark': 'Union Square',
    'originalPrice': '\$68',
    'offerPercentage': '15% OFF',
    'userCount': 140,
    'taxes': 23,
    'description':
        'Located near Union Square, this hostel provides easy access to shopping, theaters, and public transportation.',
  },
  {
    'id': '40',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.2,
    'title': 'Chinatown Hostel',
    'price': '\$48',
    'location': 'San Francisco',
    'landmark': 'Chinatown',
    'originalPrice': '\$58',
    'offerPercentage': '17% OFF',
    'userCount': 100,
    'taxes': 20,
    'description':
        'Immerse yourself in the rich culture of Chinatown with this hostel, offering authentic experiences and easy access to local markets.',
  },

  // Portland Hostels
  {
    'id': '41',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.9,
    'title': 'Friends Hostel',
    'price': '\$65',
    'location': 'Portland',
    'landmark': 'Near Forest Park',
    'originalPrice': '\$80',
    'offerPercentage': '19% OFF',
    'userCount': 210,
    'taxes': 20,
    'description':
        'An eco-friendly hostel committed to sustainability, located near the beautiful Forest Park in Portland.',
  },
  {
    'id': '42',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.7,
    'title': 'Portland Hostel',
    'price': '\$60',
    'location': 'Portland',
    'landmark': 'Downtown Portland',
    'originalPrice': '\$75',
    'offerPercentage': '20% OFF',
    'userCount': 180,
    'taxes': 21,
    'description':
        'Stay in the heart of Portland at this centrally located hostel, perfect for exploring the city\'s attractions and nightlife.',
  },
  {
    'id': '43',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.6,
    'title': 'Pearl Hostel',
    'price': '\$62',
    'location': 'Portland',
    'landmark': 'Pearl District',
    'originalPrice': '\$72',
    'offerPercentage': '17% OFF',
    'userCount': 190,
    'taxes': 22,
    'description':
        'Experience Portland\'s trendy Pearl District with this stylish hostel, offering modern amenities and easy access to galleries and restaurants.',
  },
  {
    'id': '44',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.5,
    'title': 'Gardens Hostel',
    'price': '\$58',
    'location': 'Portland',
    'landmark': 'Washington Park',
    'originalPrice': '\$68',
    'offerPercentage': '16% OFF',
    'userCount': 170,
    'taxes': 20,
    'description':
        'Located near Washington Park, this hostel offers beautiful garden views and easy access to local attractions.',
  },
  {
    'id': '45',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.4,
    'title': 'Alberta Hostel',
    'price': '\$55',
    'location': 'Portland',
    'landmark': 'Alberta  District',
    'originalPrice': '\$65',
    'offerPercentage': '15% OFF',
    'userCount': 160,
    'taxes': 20,
    'description':
        'Stay in the creative Alberta Arts District with this hostel, offering access to local art galleries, cafes, and shops.',
  },

  // Seattle Hostels
  {
    'id': '46',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.4,
    'title': 'Urban Hostel',
    'price': '\$35',
    'location': 'Seattle',
    'landmark': 'Near Pike Market',
    'originalPrice': '\$45',
    'offerPercentage': '22% OFF',
    'userCount': 130,
    'taxes': 20,
    'description':
        'A vibrant urban hostel near Seattle\'s Pike Place Market, offering a lively atmosphere and convenient location.',
  },
  {
    'id': '47',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.6,
    'title': 'Capitol Hostel',
    'price': '\$40',
    'location': 'Seattle',
    'landmark': 'Capitol Hill',
    'originalPrice': '\$50',
    'offerPercentage': '20% OFF',
    'userCount': 140,
    'taxes': 21,
    'description':
        'Experience Seattle\'s vibrant Capitol Hill neighborhood with this hostel, offering easy access to nightlife and cultural venues.',
  },
  {
    'id': '48',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.5,
    'title': 'Waterfront Hostel',
    'price': '\$42',
    'location': 'Seattle',
    'landmark': 'Seattle Waterfront',
    'originalPrice': '\$52',
    'offerPercentage': '19% OFF',
    'userCount': 150,
    'taxes': 22,
    'description':
        'Located along the Seattle Waterfront, this hostel offers stunning views and easy access to boat tours and waterfront attractions.',
  },
  {
    'id': '49',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.3,
    'title': 'Queens Hostel',
    'price': '\$38',
    'location': 'Seattle',
    'landmark': 'Queen Anne',
    'originalPrice': '\$48',
    'offerPercentage': '21% OFF',
    'userCount': 120,
    'taxes': 20,
    'description':
        'Stay in the historic Queen Anne neighborhood with this charming hostel, offering easy access to parks and local cafes.',
  },
  {
    'id': '50',
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.2,
    'title': 'Fremont Hostel',
    'price': '\$37',
    'location': 'Seattle',
    'landmark': 'Fremont',
    'originalPrice': '\$47',
    'offerPercentage': '19% OFF',
    'userCount': 115,
    'taxes': 20,
    'description':
        'Experience the quirky Fremont neighborhood with this hostel, offering unique local attractions and vibrant street art.',
  },
];

final List<Map<String, String>> cities = [
  //initial circleavatar  for cities
  {'image': 'assets/hostel2.jpeg', 'name': 'New York'},
  {'image': 'assets/hostel2.jpeg', 'name': 'Los Angeles'},
  {'image': 'assets/hostel2.jpeg', 'name': 'Chicago'},
  {'image': 'assets/hostel2.jpeg', 'name': 'Houston'},
  {'image': 'assets/hostel2.jpeg', 'name': 'Phoenix'},
  {'image': 'assets/hostel2.jpeg', 'name': 'San Francisco'},
  {'image': 'assets/hostel2.jpeg', 'name': 'Miami'},
];

final List<Map<String, dynamic>> cardData = [
  //for offer price range
  {
    'image':
        'https://cdn.pixabay.com/photo/2018/04/22/13/04/hallway-3341001_640.jpg',
    'isMainCard': true, // This card will use the main layout
    'specialOffer': 'Up to 50% off on your first booking.',
    'buttonText': 'Book Now',
    'buttonColor': Colors.orange,
  },
  {
    'image':
        'https://cdn.pixabay.com/photo/2023/09/20/20/17/wall-8265556_640.jpg',
    'isMainCard': false, // This card will use the secondary layout
    'price': '\$100/night',
    'taxes': '+ taxes',
    'buttonText': 'Explore',
    'buttonColor': Colors.blue,
  },
  {
    'image':
        'https://cdn.pixabay.com/photo/2023/09/20/20/17/wall-8265556_640.jpg',
    'isMainCard': false,
    'price': '\$120/night',
    'taxes': '+ taxes',
    'buttonText': 'Explore',
    'buttonColor': Colors.blue,
  },
  {
    'image':
        'https://cdn.pixabay.com/photo/2023/09/20/20/17/wall-8265556_640.jpg',
    'isMainCard': false,
    'price': '\$80/night',
    'taxes': '+ taxes',
    'buttonText': 'Explore',
    'buttonColor': Colors.green,
  },
  {
    'image':
        'https://cdn.pixabay.com/photo/2023/09/20/20/17/wall-8265556_640.jpg',
    'isMainCard': false,
    'price': '\$150/night',
    'taxes': '+ taxes',
    'buttonText': 'Explore',
    'buttonColor': Colors.red,
  },
  {
    'image':
        'https://cdn.pixabay.com/photo/2023/09/20/20/17/wall-8265556_640.jpg',
    'isMainCard': false,
    'price': '\$90/night',
    'taxes': '+ taxes',
    'buttonText': 'Explore',
    'buttonColor': Colors.purple,
  },
];

//filter button data

final buttonData = [
  {
    'icon': Icons.keyboard_arrow_down_sharp,
    'text': 'Sort',
  },
  {
    'icon': Icons.keyboard_arrow_down_sharp,
    'text': 'Locality',
  },
  {
    'icon': Icons.keyboard_arrow_down_sharp,
    'text': 'Price',
  },
  {
    'icon': Icons.keyboard_arrow_down_sharp,
    'text': 'Townhouse',
  },
  {
    'icon': Icons.keyboard_arrow_down_sharp,
    'text': 'Trending',
  },
  {
    'icon': Icons.keyboard_arrow_down_sharp,
    'text': 'collection',
  },
];

final List<String> places = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
];
