final List<Map<String, dynamic>> hostels = [
  {
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.5,
    'title': 'Cozy Hostel',
    'price': '\$50/night',
    'location': 'New York',
    'originalPrice': '\$60/night',
    'offerPercentage': '20% OFF',
    'userCount': 120,
  },
  {
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.2,
    'title': 'Modern Hostel',
    'price': '\$60/night',
    'location': 'Los Angeles',
    'originalPrice': '\$75/night',
    'offerPercentage': '15% OFF',
    'userCount': 95,
  },
  {
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.8,
    'title': 'Luxury Hostel',
    'price': '\$80/night',
    'location': 'Chicago',
    'originalPrice': '\$100/night',
    'offerPercentage': '20% OFF',
    'userCount': 200,
  },
  {
    'imageUrl': 'assets/hostel1.jpg',
    'rating': 4.0,
    'title': 'Budget Hostel',
    'price': '\$30/night',
    'location': 'Houston',
    'originalPrice': '\$40/night',
    'offerPercentage': '25% OFF',
    'userCount': 80,
  },
];

final List<Map<String, String>> cities = [
  {'image': 'assets/hostel2.jpeg', 'name': 'New York'},
  {'image': 'assets/hostel2.jpeg', 'name': 'Los Angeles'},
  {'image': 'assets/hostel2.jpeg', 'name': 'Chicago'},
  {'image': 'assets/hostel2.jpeg', 'name': 'Houston'},
  {'image': 'assets/hostel2.jpeg', 'name': 'Phoenix'},
  {'image': 'assets/hostel2.jpeg', 'name': 'San Francisco'},
  {'image': 'assets/hostel2.jpeg', 'name': 'Miami'},
];
